word_src : "words_250000_train.txt"
num_env: 100
max_lives: 6
win_reward: 100
correct_reward: 20
repeated_guessing_penalty: -100
lose_reward: -100
false_reward: -50
env_verbose: False

vocab_size: 28
embed_size: 128
num_heads: 16
key_dim: 2
base_model_wts: "base_model_wts/base_model_weights_16x128.h5"

gamma : 0.99
epsilon : 1.0 
epsilon_min:  0.1  
epsilon_max : 1.0 
epsilon_random_frames : 50000
epsilon_greedy_frames : 1000000.0
max_memory_length : 100000
train_record_steps: 400
eval_record_steps: 50
batch_size: 4000
epochs: 30

train_steps: 10
